# Generated by Django 4.1.3 on 2022-11-18 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundamentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={},
        ),
    ]
